var icons = {
    statusIcons: {
        Playing: '<i class="lnir lnir-play"></i>',
        Completed: '<i class="lnir lnir-checkmark"></i>',
        Unplayed: '<i class="lnir lnir-stop"></i>',
        'Not Finished': '<i class="lnir lnir-pause"></i>'
    },
    genreIcons: {
        Action: '',
        Indie: '',
        Adventure: '',
        RPG: '<i class="lnir lnir-scroll"></i>',
        Strategy: '',
        Shooter: '../images/shooter.png',
        Casual: '',
        Simulation: '',
        Puzzle: '',
        Arcade: '',
        Platformer: '',
        Racing: '',
        Sports: '',
        'Massively Multiplayer': '',
        Fighting: '',
        lnirmily: '',
        'Board Games': '',
        Educational: '',
        Card: '',
    },
    platformIcons: {
        PC: '',
        'Playstation 5': '',
        'Playstation 4': '',
        'Xbox One': '',
        'Xbox Series S/X': '',
        'Nintendo Switch': '',
        Mobile: '',
        'Nintendo 3DS': '',
        'Nintendo DS': '',
        'Xbox 360': '',
        Xbox: '',
        'Playstation 3': '',
        'Playstation 2': '',
        Playstation: '',
        'PS Vita': '',
        PSP: '',
        'Wii U': '',
        Wii: '',
        GameCube: '',
        'Nintendo 64': '',
        'Game Boy Advance': '',
        'Game Boy Color': '',
        'Game Boy': '',
        SNES: '',
        NES: ''
    }
};
export default icons;