var icons = {
    statusIcons: {
        'Up Next': '<i class="lnir lnir-power-switch"></i>',
        Playing: '<i style="color:green;" class="lnir lnir-power-switch"></i>',
        Completed: '<i class="lnir lnir-medal"></i>',
        Unplayed: '<i style="color:red;" class="lnir llnir-power-switch"></i>',
        'Not Finished': '<i style="color:yellow;" class="lnir lnir-power-switch"></i>'
    },
    genreIcons: {
        Action: '<i class="lnir lnir-bolt-alt"></i>',
        Adventure: '<i class="lnir lnir-backpack"></i>',
        RPG: '<i class="lnir lnir-library"></i>',
        Strategy: '<i class="lnir lnir-rook"></i>',
        Shooter: '<i class="lnir lnir-target"></i>',
        Simulation: '<i class="lnir lnir-strategy"></i>',
        Puzzle: '<i class="lnir lnir-cubes"></i>',
        Arcade: '<i class="lnir lnir-diamond-alt"></i>',
        Platformer: '<i class="lnir lnir-menu-alt-4"></i>',
        Racing: '<i class="lnir lnir-car-alt"></i>',
        Sports: '<i class="lnir lnir-basketball"></i>',
        'Massively Multiplayer': '<i class="lnir lnir-network"></i>',
        Fighting: '<i class="lnir lnir-users-2"></i>',
    },
    platformIcons: {
        PC: '',
        'Playstation 5': '',
        'Playstation 4': '',
        'Xbox One': '',
        'Xbox Series S/X': '',
        'Nintendo Switch': '',
        Mobile: '',
        'Nintendo 3DS': '',
        'Nintendo DS': '',
        'Xbox 360': '',
        Xbox: '',
        'Playstation 3': '',
        'Playstation 2': '',
        Playstation: '',
        'PS Vita': '',
        PSP: '',
        'Wii U': '',
        Wii: '',
        GameCube: '',
        'Nintendo 64': '',
        'Game Boy Advance': '',
        'Game Boy Color': '',
        'Game Boy': '',
        SNES: '',
        NES: ''
    }
};
export default icons;